services:
  - type: web
    name: lf-api
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONIOENCODING
        value: utf-8
